apiVersion: v1
kind: Secret
metadata:
  name: auth
  annotations:
    avp.kubernetes.io/path: "secrets/avp/data/example/example-auth"
type: Opaque
stringData:
  username: Administrator
  password: <password>
